#ifndef ERROR_H
#define ERROR_H

enum error
{
	ERROR = 0,
	SUCCESS = 1,
	VICTORY,
	ERROR_OPEN_FILE,
	ERROR_CLOSE_FILE,
	ERROR_MALLOC,
	ERROR_DO_PLAY,
	ERROR_MALLOC_INITILIAZE,
	ERROR_MALLOC_INITILIAZE_PLAYER,
	ERROR_NOT_ENOUGH_PLAYER,
	ERROR_TOO_MANY_PLAYER,
	ERROR_NOT_ENOUGH_CARD,
	ERROR_NOT_ENOUGH_PATH_CARD,
	ERROR_OPEN_SO,
	ERROR_NOT_SO_FILE,
	ERROR_PARSE,
	ERROR_PARSE_MALLOC_INITIALIZE,
	ERROR_PARSE_MALLOC,
	ERROR_PARSE_WRONG_FIRST_NUMBER,
	ERROR_PARSE_WRONG_SECOND_NUMBER,
	ERROR_PARSE_INVALID_BOARD,
	ERROR_PARSE_TYPE,
	ERROR_PARSE_NOT_A_TOKEN,
	ERROR_PARSE_NOT_TOKEN_ALPHA,
	ERROR_PARSE_NOT_TOKEN_NUMBER,
	ERROR_PARSE_COMMENT,
	ERROR_PARSE_TWO_STARTS,
	ERROR_PARSE_EXPECTING_CARD_ID,
	ERROR_PARSE_INVALID_CARD_ID,
	ERROR_PARSE_EXPECTING_NUMBER_AFTER_CARD_ID,
	ERROR_DL_SYM,
	ERROR_PLAY
};


#endif
